---
- name: Copy main config file
  become: yes
  become_user: root
  template:
    src: "templates/etc/collectd/collectd.conf.j2"
    dest: "/etc/collectd/collectd.conf"
    mode: 0644
    owner: root
    group: root